---
- match:
    dependency_type: all
    update_type: security:*
- match:
    dependency_type: production
    update_type: semver:minor
- match:
    dependency_type: development
    update_type: semver:major
