###
# @see https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates
##
---
version: 2
registries:
  wpmudev:
    type: composer-repository
    url: https://wpmudev.com:443
    username: ${{ secrets.WPMUDEV_API_KEY }}
    password: ''
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: all
    labels:
      - maintenance
      - dependencies
    registries:
      - wpmudev
